CREATE DATABASE Loja_T
GO

USE Loja_T

CREATE TABLE Cliente(
	ID_Cliente INT IDENTITY(1,1) PRIMARY KEY,
	Nome NVARCHAR(255) NOT NULL,
);

SELECT * FROM Cliente

CREATE TABLE Produto(
	ID_Produto	INT IDENTITY(1,1	) PRIMARY KEY,
	Nome	 NVARCHAR(100)	NOT NULL UNIQUE,
	Preco	 DECIMAL	(6,2)
);

SELECT * FROM Produto

CREATE TABLE Pedido(
	ID_Pedido	INT IDENTITY(1,1)	 PRIMARY KEY,
	Data_Horario	DATETIME	 NOT NULL,
	ID_Cliente INT NOT NULL,
	ID_Produto INT NOT NULL,

	FOREIGN KEY(ID_Cliente) REFERENCES Cliente(ID_Cliente),
	FOREIGN KEY(ID_Produto) REFERENCES Produto(ID_Produto),

);

ALTER TABLE Pedido
ALTER COLUMN Data_Horario DATETIME2 NOT NULL;