	--CRIA UM LOGIN DE USUARIO
	CREATE LOGIN thiago	WITH PASSWORD = '123';

	--CRIA UM USUARIO DENTRO DE UM BANCO DE DADOS
	CREATE USER thiago FOR LOGIN thiago;

	--COMANDO DENY - BLOQUEIA O ACESSO
	DENY INSERT, UPDATE , DELETE
	TO thiago;

	--COMANDO REVOKE - REVERTE A PERMISSÃO DO USUÁRIO
	REVOKE INSERT , UPDATE , DELETE
	TO thiago;

	CREATE TABLE Usuario(
	id INT NOT NULL
	);

	SELECT * FROM Usuario

	--COMANDO GRANT
	GRANT SELECT TO thiago